all_plus_signal:
  combine_tagging: false
  control_regions: &CRS [cr_w, cr_t, cr_z]
  fixed_backgrounds: &FB [other, QCD]
  signal_regions: &SR [signal_mct150]
  combined_backgrounds: &COMBINE
    top: [singleTop]
  systematics: &BASESYST
    - jes
    - jer
    - jvf
    - pu
    - el
    - mu
    - met
    - metres
    - eglow
    - mscale
    - egzee
    - c
    - b
    - u
    - t
    - flat_other
    - mettrig
    - signal_isr
    - signal_xsec
    - theory_Wjets
    - theory_Zjets
    - theory_top

all:
  combine_tagging: false
  control_regions: &CRS [cr_w, cr_t, cr_z]
  fixed_backgrounds: &FB [other, QCD]
  signal_regions: &SR [signal_mct150]
  combined_backgrounds: &COMBINE
    top: [singleTop]
  systematics: &BASESYST
    - jes
    - jer
    - jvf
    - pu
    - el
    - mu
    - met
    - metres
    - eglow
    - mscale
    - egzee
    - c
    - b
    - u
    - t
    - flat_other
    - mettrig
    - theory_Wjets
    - theory_Zjets
    - theory_top

experimental:
  combine_tagging: false
  control_regions: *CRS
  fixed_backgrounds: *FB
  signal_regions: *SR
  combined_backgrounds: *COMBINE
  systematics:
    - jes
    - jer
    - jvf
    - pu
    - el
    - mu
    - met
    - metres
    - eglow
    - mscale
    - egzee
    - c
    - b
    - u
    - t

none:
  combine_tagging: false
  control_regions: *CRS
  fixed_backgrounds: *FB
  signal_regions: *SR
  combined_backgrounds: *COMBINE
  systematics: []

