crw_l1pt50:
  combine_tagging: false
  control_regions: &CRS [cr_w, cr_t, cr_z]
  fixed_backgrounds: &FB [other, QCD]
  signal_regions: &SR [signal_mct150]
  validation_regions: &VR [fr_mct, fr_mcc]
  combined_backgrounds: &COMBINE
    top: [singleTop]
  systematics: &BASESYST
    - jes
    - jer
    - jvf
    - pu
    - el
    - mu
    - met
    - metres
    - eglow
    - mscale
    - egzee
    - c
    - b
    - u
    - t
    - flat_other
    - mettrig
    - signal_isr
    - theory_Wjets
    - theory_Zjets
    - theory_top

crw_l1pt25:
  combine_tagging: false
  control_regions: [cr_w_l1pt25, cr_t, cr_z]
  fixed_backgrounds: *FB
  signal_regions: *SR
  validation_regions: *VR
  combined_backgrounds: *COMBINE
  systematics: *BASESYST
