with_ttbar_rw:
  control_regions: &CRS [cr_w, cr_t, cr_z]
  fixed_backgrounds: &FB [other, QCD]
  signal_regions: [signal_mct150]
  validation_regions: &VR [signal_mct200, signal_mct250, fr_mct, fr_mcc]
  combined_backgrounds: &COMBINE
    top: [singleTop]
  signal_systematics: &SIGSYST
    - signal_xsec
  systematics: &BASESYST
    - jes
    - jer
    - jvf
    - pu
    - el
    - mu
    - met
    - metres
    - eglow
    - mscale
    - egzee
    - c
    - b
    - u
    - t
    - flat_other
    - mettrig
    - signal_isr
    - theory_Wjets
    - theory_Zjets
    - theory_top

