# NOTE: none of these configurations should be used for exclusion,
# since they all use multiple signal regions. They exist for the
# sake of ``background-only'' (control region) fits.
vrcrsr:
  combine_tagging: false
  control_regions: &CRS [cr_w, cr_t, cr_z]
  fixed_backgrounds: &FB [other, QCD]
  signal_regions: &SR [signal_mct150, signal_mct200, signal_mct250]
  validation_regions: &VR
    - fr_mct
    - fr_mcc
    - cr_z_nicola
    - cr_t_nicola
    - cr_w_nicola
    - cr_z_metola
    - cr_t_metola
    - cr_w_metola
  combined_backgrounds: &COMBINE
    top: [singleTop]
  systematics: &BASESYST
    - jes
    - jer
    - jvf
    - pu
    - el
    - mu
    - met
    - metres
    - eglow
    - mscale
    - egzee
    - c
    - b
    - u
    - t
    - flat_other
    - mettrig
    - signal_isr
    - theory_Wjets
    - theory_Zjets
    - theory_top

l1pt25:
  combine_tagging: false
  control_regions: &CRS25 [cr_w_l1pt25, cr_t, cr_z]
  fixed_backgrounds: *FB
  signal_regions: *SR
  validation_regions: *VR
  combined_backgrounds: *COMBINE
  systematics: *BASESYST

nicola:
  combine_tagging: false
  control_regions:
    - cr_z_nicola
    - cr_t_nicola
    - cr_w_nicola
  fixed_backgrounds: *FB
  signal_regions: *SR
  combined_backgrounds: *COMBINE
  systematics: *BASESYST

metola:
  combine_tagging: false
  control_regions:
    - cr_z_metola
    - cr_t_metola
    - cr_w_metola
  fixed_backgrounds: *FB
  signal_regions: *SR
  combined_backgrounds: *COMBINE
  systematics: *BASESYST
